INSERT INTO USERS (ID, USERNAME, ENABLED) VALUES (1, 'admin', true);
INSERT INTO USERS (ID, USERNAME, ENABLED) VALUES (2, 'analyst', true);

INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_ANALYST');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_ROLE (USERS_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLE (USERS_ID, ROLE_ID) VALUES (2, 1);
